# Generated by Django 4.2.21 on 2026-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='分类名')),
                ('color', models.CharField(default='#16a085', max_length=24, verbose_name='主题色')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='留言')),
                ('is_visible', models.BooleanField(default=True, verbose_name='前台显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Qi Zhang', max_length=64, verbose_name='姓名')),
                ('headline', models.CharField(max_length=160, verbose_name='一句话介绍')),
                ('bio', models.TextField(verbose_name='关于我')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='所在地')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='链接别名')),
                ('summary', models.CharField(max_length=260, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover', models.URLField(blank=True, verbose_name='封面图')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔', max_length=160, verbose_name='标签')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
