# Generated by Django 4.2.21 on 2026-05-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_message_parent_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='兼容旧数据，用逗号分隔', max_length=160, verbose_name='旧标签文本'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='链接别名')),
                ('color', models.CharField(default='#2f6df6', max_length=24, verbose_name='主题色')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.tag', verbose_name='上级标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'ordering': ['parent__id', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tag_nodes',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='多层级标签'),
        ),
    ]
