# Generated by Django 4.2.21 on 2026-05-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_tags_tag_article_tag_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='曲名')),
                ('audio', models.FileField(upload_to='music/', verbose_name='音频文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '背景音乐',
                'verbose_name_plural': '背景音乐',
                'ordering': ['-created_at'],
            },
        ),
    ]
