# Generated by Django 4.2.21 on 2026-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_backgroundmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='life/', verbose_name='照片')),
                ('note', models.TextField(verbose_name='当时想说的话')),
                ('taken_at', models.DateField(verbose_name='记录日期')),
                ('is_published', models.BooleanField(default=True, verbose_name='前台显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '生活记录',
                'verbose_name_plural': '生活记录',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
    ]
