# Generated by Django 4.2.21 on 2026-05-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_liferecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundmusic',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': '背景音乐', 'verbose_name_plural': '背景音乐'},
        ),
        migrations.AddField(
            model_name='backgroundmusic',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='播放顺序'),
        ),
    ]
