# Generated by Django 4.2.21 on 2026-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_backgroundmusic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_file',
            field=models.FileField(blank=True, upload_to='article_covers/', verbose_name='本地封面图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.URLField(blank=True, verbose_name='外站封面图链接'),
        ),
    ]
